version: "3.9"
services:
  database:
    image: postgres:15.2-alpine
    environment: 
      - POSTGRES_USER=yolo-user
      - POSTGRES_PASSWORD=yolo-password
      - POSTGRES_DB=yolo-db
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata: